### ISSUE TITLE
可以在 Folders 這兩個位置加多些空間嗎?

### ISSUE THREAD

**Issue by ForGx3** [xiangfeidexiaohuo/xiangfeidexiaohuo.github.io#3]
Hello, 剛剛安裝你的版本 ClassicFolders 3(RootHide)
使用上感覺沒什麼問題, 很不錯!

但在打開 folders 時, 圖片上這兩個位置能不能再加多些空間?
因為感覺這裡太過狹窄了, folders 的名字有時候會給 badges 擋住了...

謝謝你了. :)

![ClassicFolders 3](https://github.com/user-attachments/assets/3ba2b87a-d648-4264-a3a7-e71bec4d954a)

**Comment by xiangfeidexiaohuo** [comment]
> Hello, 剛剛安裝你的版本 ClassicFolders 3(RootHide) 使用上感覺沒什麼問題, 很不錯!
> 
> 但在打開 folders 時, 圖片上這兩個位置能不能再加多些空間? 因為感覺這裡太過狹窄了, folders 的名字有時候會給 badges 擋住了...
> 
> 謝謝你了. :)
> 
> ![ClassicFolders 3](https://private-user-images.githubusercontent.com/52027453/367580423-3ba2b87a-d648-4264-a3a7-e71bec4d954a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY2MDA0NDYsIm5iZiI6MTcyNjYwMDE0NiwicGF0aCI6Ii81MjAyNzQ1My8zNjc1ODA0MjMtM2JhMmI4N2EtZDY0OC00MjY0LWEzYTctZTcxYmVjNGQ5NTRhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTE3VDE5MDkwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVmN2JhZGQ1OTc1ZTJlNjFmZTg5MTAxMGYwZWY1NmUxOWQ3NDA0MWNiYTEyNjk3Zjk3YWQwYzJhNDM1MTM0ZTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.OEJltogEj4wI11tyqvqWwf2f925L62vlkA_9TizQhdE)

最原始的cf3就是这样，你说的底部位置就只能这样，顶部那个文件夹名称，后面看看怎么改，看着舒服点。

**Comment by ForGx3** [comment]
> > Hello, 剛剛安裝你的版本 ClassicFolders 3(RootHide) 使用上感覺沒什麼問題, 很不錯!
> > 但在打開 folders 時, 圖片上這兩個位置能不能再加多些空間? 因為感覺這裡太過狹窄了, folders 的名字有時候會給 badges 擋住了...
> > 謝謝你了. :)
> > ![ClassicFolders 3](https://private-user-images.githubusercontent.com/52027453/367580423-3ba2b87a-d648-4264-a3a7-e71bec4d954a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY2MDA0NDYsIm5iZiI6MTcyNjYwMDE0NiwicGF0aCI6Ii81MjAyNzQ1My8zNjc1ODA0MjMtM2JhMmI4N2EtZDY0OC00MjY0LWEzYTctZTcxYmVjNGQ5NTRhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTE3VDE5MDkwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVmN2JhZGQ1OTc1ZTJlNjFmZTg5MTAxMGYwZWY1NmUxOWQ3NDA0MWNiYTEyNjk3Zjk3YWQwYzJhNDM1MTM0ZTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.OEJltogEj4wI11tyqvqWwf2f925L62vlkA_9TizQhdE)
> 
> 最原始的cf3就是这样，你说的底部位置就只能这样，顶部那个文件夹名称，后面看看怎么改，看着舒服点。

好的, 謝謝你用心維護這些插件 :)
